#!/bin/bash
# gwsm install script
# Usage:
#   sudo ./install.sh               # installs to /usr/local/bin (system-wide)
#   INSTALL_DIR=~/.local/bin ./install.sh   # installs to custom location
set -e

INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Installing gwsm..."

# Install binary
install -Dm755 "$SCRIPT_DIR/gwsm" "$INSTALL_DIR/gwsm"
echo "  Binary  -> $INSTALL_DIR/gwsm"

# Generate service file with the correct binary path substituted in.
SERVICE_SRC="$SCRIPT_DIR/gwsm.service"
SERVICE_CONTENT=$(sed "s|{{GWSM_BIN}}|$INSTALL_DIR/gwsm|g" "$SERVICE_SRC")

if [ "$(id -u)" -eq 0 ]; then
    # Root install: place unit in system-wide user service directory.
    SERVICE_DIR="/usr/lib/systemd/user"
    mkdir -p "$SERVICE_DIR"
    echo "$SERVICE_CONTENT" > "$SERVICE_DIR/gwsm.service"
    echo "  Service -> $SERVICE_DIR/gwsm.service"
    systemctl daemon-reload 2>/dev/null || true
else
    # Non-root install: place unit in the current user's directory.
    SERVICE_DIR="$HOME/.config/systemd/user"
    mkdir -p "$SERVICE_DIR"
    echo "$SERVICE_CONTENT" > "$SERVICE_DIR/gwsm.service"
    echo "  Service -> $SERVICE_DIR/gwsm.service"
    systemctl --user daemon-reload 2>/dev/null || true
fi

# Generate uninstall.sh alongside this script, recording exactly what was
# installed and where so the user can cleanly remove it later.
UNINSTALL="$SCRIPT_DIR/uninstall.sh"
cat > "$UNINSTALL" << EOF
#!/bin/bash
# gwsm uninstall script — generated by install.sh
set -e

echo "Uninstalling gwsm..."

# Stop and disable the service if it is running.
systemctl --user disable --now gwsm 2>/dev/null || true

# Remove the binary.
if [ -f "$INSTALL_DIR/gwsm" ]; then
    rm -f "$INSTALL_DIR/gwsm"
    echo "  Removed $INSTALL_DIR/gwsm"
fi

# Remove the service unit.
if [ -f "$SERVICE_DIR/gwsm.service" ]; then
    rm -f "$SERVICE_DIR/gwsm.service"
    echo "  Removed $SERVICE_DIR/gwsm.service"
fi

# Reload systemd so it forgets the unit.
EOF

# Append the correct daemon-reload call based on install type.
if [ "$(id -u)" -eq 0 ]; then
    cat >> "$UNINSTALL" << 'EOF'
systemctl daemon-reload 2>/dev/null || true
EOF
else
    cat >> "$UNINSTALL" << 'EOF'
systemctl --user daemon-reload 2>/dev/null || true
EOF
fi

cat >> "$UNINSTALL" << 'EOF'

echo ""
echo "gwsm uninstalled."
echo ""
EOF

chmod 755 "$UNINSTALL"
echo "  Uninstaller -> $SCRIPT_DIR/uninstall.sh"

echo ""
echo "Done. To enable the auto-restore daemon:"
echo ""
echo "  systemctl --user enable --now gwsm"
echo ""
echo "To uninstall later, run:"
echo ""
echo "  $SCRIPT_DIR/uninstall.sh"
echo ""
